import { jsPDF } from "jspdf";

import type { TranscriptResponse } from "@/lib/types";
import { formatTimestamp, slugify } from "@/lib/utils";

interface PdfLayout {
  marginX: number;
  marginTop: number;
  marginBottom: number;
  lineHeight: number;
  pageWidth: number;
  pageHeight: number;
  contentWidth: number;
}

/**
 * Export a transcript as a nicely formatted, multi-page PDF using jsPDF.
 *
 * The document contains a header (title, channel, duration, source, generated
 * date) followed by the transcript body. Each segment is prefixed with its
 * timestamp and the body text is wrapped to the page width with automatic
 * page breaks.
 */
export function exportTranscriptToPdf(data: TranscriptResponse): void {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
    compress: true,
  });

  const layout: PdfLayout = (() => {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginX = 48;
    return {
      marginX,
      marginTop: 56,
      marginBottom: 56,
      lineHeight: 16,
      pageWidth,
      pageHeight,
      contentWidth: pageWidth - marginX * 2,
    };
  })();

  let cursorY = layout.marginTop;

  const ensureSpace = (needed: number): void => {
    if (cursorY + needed > layout.pageHeight - layout.marginBottom) {
      doc.addPage();
      cursorY = layout.marginTop;
    }
  };

  const writeWrapped = (
    text: string,
    options: {
      fontSize: number;
      fontStyle?: "normal" | "bold" | "italic";
      color?: [number, number, number];
      gapAfter?: number;
      lineHeight?: number;
    },
  ): void => {
    const {
      fontSize,
      fontStyle = "normal",
      color = [20, 20, 20],
      gapAfter = 0,
      lineHeight = layout.lineHeight,
    } = options;

    doc.setFont("helvetica", fontStyle);
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);

    const lines = doc.splitTextToSize(text, layout.contentWidth) as string[];
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, layout.marginX, cursorY);
      cursorY += lineHeight;
    }
    cursorY += gapAfter;
  };

  // ---- Header ----------------------------------------------------------
  writeWrapped(data.title || "Untitled video", {
    fontSize: 18,
    fontStyle: "bold",
    color: [17, 17, 17],
    lineHeight: 22,
    gapAfter: 4,
  });

  const metaParts: string[] = [];
  if (data.channel) metaParts.push(data.channel);
  if (data.duration) metaParts.push(`Duration: ${data.duration}`);
  metaParts.push(
    `Source: ${data.source === "whisper" ? "AI transcription (Whisper)" : "Captions"}`,
  );
  if (data.language) metaParts.push(`Language: ${data.language}`);

  writeWrapped(metaParts.join("  •  "), {
    fontSize: 10,
    color: [110, 110, 110],
    lineHeight: 14,
    gapAfter: 2,
  });

  writeWrapped(
    `https://www.youtube.com/watch?v=${data.video_id}`,
    {
      fontSize: 9,
      color: [180, 30, 30],
      lineHeight: 13,
      gapAfter: 2,
    },
  );

  writeWrapped(
    `Generated by TubeTranscript on ${new Date().toLocaleString()}`,
    {
      fontSize: 8,
      fontStyle: "italic",
      color: [150, 150, 150],
      lineHeight: 12,
      gapAfter: 10,
    },
  );

  // Divider line.
  ensureSpace(12);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.75);
  doc.line(layout.marginX, cursorY, layout.pageWidth - layout.marginX, cursorY);
  cursorY += 16;

  // ---- Body ------------------------------------------------------------
  const segments = data.transcript ?? [];

  if (segments.length > 0) {
    for (const segment of segments) {
      const stamp = `[${formatTimestamp(segment.start)}]`;
      const body = segment.text?.trim() ?? "";
      if (!body) continue;

      // Timestamp on its own short line, then the text. Keep them together
      // by reserving space for at least two lines.
      ensureSpace(layout.lineHeight * 2);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(180, 30, 30);
      doc.text(stamp, layout.marginX, cursorY);
      cursorY += 13;

      writeWrapped(body, {
        fontSize: 11,
        color: [30, 30, 30],
        lineHeight: 15,
        gapAfter: 8,
      });
    }
  } else if (data.text) {
    // Fall back to the flat text blob if no segments are present.
    writeWrapped(data.text, {
      fontSize: 11,
      color: [30, 30, 30],
      lineHeight: 15,
    });
  } else {
    writeWrapped("No transcript content available.", {
      fontSize: 11,
      fontStyle: "italic",
      color: [120, 120, 120],
    });
  }

  // ---- Page numbers ----------------------------------------------------
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    const label = `Page ${page} of ${pageCount}`;
    const textWidth = doc.getTextWidth(label);
    doc.text(
      label,
      layout.pageWidth - layout.marginX - textWidth,
      layout.pageHeight - 24,
    );
  }

  doc.save(`${slugify(data.title || data.video_id)}-transcript.pdf`);
}
